### ISSUE TITLE
Attempt: Focus tree backgrounds

### ISSUE THREAD

**Issue by Helliaca** [HoI4-LOTRMod-Team/HoI4-LotrMod#95]
I recently discovered that you can insert scripted GUIs into other GUI files. (See lothlorien_influence_focustree_scripted_gui) for how it's done.

This means the we could, potentially, add background images /categories (like in the tech-trees) to focus-trees on a per-country basis.

Might be worth experimenting with and seeing what comes of it. Afaik no other mod has done this, so it would be something nice and unique

**Comment by Cevedale** [comment]
Really interesting! The prospect of integrating scripted GUIs into focus-trees, as demonstrated by the lothlorien_influence_focustree_scripted_gui, opens up exciting possibilities for enhancing the visual and thematic aspects of our mod. The idea of incorporating background images and categories on a per-country basis is intriguing and could provide a unique and immersive experience for players. Experimenting with this feature is definitely worth pursuing, and the fact that no other mod has ventured into this territory adds an element of novelty to our project. Let's explore the potential and see how we can leverage this innovation to create a distinctive and engaging modding experience.

**Comment by Helliaca** [comment]
This is still a potential idea, but any sensible background would be a very large image. I'll keep it in mind, but I'm closing this issue for now
